version: "3"

services:
  oss-rpc:
    build:
        context: .
        dockerfile: ./app/oss/rpc/Dockerfile
    ports:
      - "8001:8001"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  user-rpc:
    build:
        context: .
        dockerfile: ./app/user/rpc/Dockerfile
    ports:
      - "8002:8002"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  follow-rpc:
    build:
      context: .
      dockerfile: ./app/follow/rpc/Dockerfile
    ports:
        - "8003:8003"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  web-api:
    build:
      context: .
      dockerfile: ./app/web/api/Dockerfile
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"

